LAB3/todo/main/urls.py
from django.urls import path
from main import views

app_name='main'
urlpatterns = [
    path('', views.MainPage.as_view(), name='index'),
    path('<int:id>/delete', views.delete, name='delete'),
    path('<int:id>/update', views.update, name='update'),
    path('add/', views.add, name='add')
]

LAB3/todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from todo import settings
from main import views

urlpatterns = [
    path('todos/', include('main.urls')),
    path('admin/', admin.site.urls),
    path('', views.index)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

LAB3/todo/main/models.py
from django.db import models

class Main(models.Model):
    name = models.CharField(max_length=150)
    time_cre = models.DateTimeField('Created', auto_now_add=True)
    time_upd = models.DateTimeField('Updated', auto_now=True)
    finished = models.BooleanField(default=False)

    def __str__(self):
        return self.title

LAB3/todo/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from main.models import Main


class MainPage(generic.ListView):
    template_name = 'todos/index.html'
    context_object_name = 'todo_list'

    def get_queryset(self):
        return Main.objects.order_by('-time_cre')


def add(request):
    name = request.POST['title']
    Main.objects.create(name=name)
    return redirect('main:index')


def delete(request, id):
    todo = get_object_or_404(Main, pk=id)
    todo.delete()
    return redirect('main:index')


def update(request, id):
    todo = get_object_or_404(Main, pk=id)
    isCompleted = request.POST.get('finished', False)
    if isCompleted == 'on':
        isCompleted = True

    todo.finished = isCompleted

    todo.save()
    return redirect('main:index')


def index(request):
    return redirect('/todos')

LAB3/todo/main/templates/todos/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  {% block title %}
  {% endblock %}
</head>
<body>
    <header class="mb-5 p-3 bg-dark text-light text-center">
    </header>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

LAB3/todo/main/templates/todos/index.html
{% extends 'todos/base.html' %}

{% block title %}
<title>Todo list</title>
{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="offset-md-2 col-lg-9">
      <div class="page-header">
        <h1>
          Todo List
        </h1>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="offset-md-2 col-lg-9">
      <form method="post" action="{% url 'main:add' %}">
        {% csrf_token %}
        <div class="form-row">
          <div class="col-md-6">
            <input type="text" class="form-control" name="title" placeholder="Do laundry" required>
          </div>
          <div class="col-md-6">
            <button type="submit" name="submit" class="btn btn-outline-primary">
              Add
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <hr />

  <div class="row">
    <div class="offset-md-2 col-lg-6">
      <div class="list-group">
        {% for todo in todo_list %}
        <div class="list-group-item {% if todo.isCompleted %} todo-complete {% endif %}">
          <form style="display: inline;" method="post" action="{% url 'main:update' todo.id %}">
            {% csrf_token %}
            <input type="checkbox" name="finished" onchange="this.form.submit()" {% if todo.finished %} checked
              {% endif %} class="todo-status-checkbox"
              title="{% if not todo.finished %} mark as done {% else %} mark undone {% endif %}">
          </form>
          {{ todo.name }}
          <a href="{% url 'main:delete' todo.id %}" title="Delete">
            <i class="far fa-trash-alt"></i>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}